# Site settings

url: http://www.erminmuratovic.com
baseurl: ""
title: Ermin Muratovic Homepage
description: Ermin Muratovic Portfolio Homepage

languages: ["en", "de"]
exclude_from_localizations: ["assets", "components"]
defaultLang: en
languageNames:
  de: Deutsch
  en: English
destination: ./docs # Github Pages custom build, because of additional plugins

author:
  name: Ermin Muratovic

google_analytics: "UA-59508056-1"

#social-network-links:
#  rss: true
#  email: "ermin@muratovic.at"
#  facebook: ermin.muratovic
#  github: ermin-muratovic
#  twitter: erminm
#  linkedin: ermin-muratovic
#  instagram: erminmurat

#share-links-active:
#  twitter: true
#  facebook: true
#  linkedin: true

timezone: Europe/Vienna
markdown: kramdown
highlighter: rouge
# permalink: /:year-:month-:day-:title/
# paginate: 5

kramdown:
  input: GFM

plugins:
#  - jekyll-multiple-languages-plugin
#  - jekyll-paginate